name: Node.js CI/CD

on:
  push:
    branches: [test1, test2, master]
  pull_request:
    branches: [test1, test2, master]

jobs:
  block-pull-request-manually:
    runs-on: ubuntu-latest
    if: always() && (github.event_name == 'pull_request' && github.base_ref == 'master')
    steps:
      - name: Block manual merges to master
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] && [ "${{ github.base_ref }}" == "master" ]; then
            echo "Manual merges to master are not allowed. Please use the CI/CD pipeline."
            exit 1
          else
            echo "This check only applies to PRs targeting master"
          fi
  block-push-manually:
    runs-on: ubuntu-latest
    if: always() && (github.event_name == 'push' && github.ref == 'refs/heads/master')
    steps:
      - name: Block direct pushes to master
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "Direct pushes to master are not allowed. Please create a pull request instead."
            exit 1
          else
            echo "This check only applies to pushes to master"
          fi
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  verify-branch-merge:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Verify branch merge
        if: ${{ needs.build-and-test.result == 'success' }}
        run: echo "Branch merge verified successfully."