name: Node.js CI/CD

on:
  push:
    branches: [test1, test2, master]
  pull_request:
    branches: [test1, test2, master]

jobs:
  block-pull-request-manually:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'master'
    steps:
      - name: Block manual merges to master
        run: |
          echo "Manual merges to master are not allowed. Please use the CI/CD pipeline."
          
  block-push-manually:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Block direct pushes to master
        run: |
          echo "Direct pushes to master are not allowed. Please create a pull request instead."
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  verify-branch-merge:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Verify branch merge
        if: ${{ needs.build-and-test.result == 'success' }}
        run: echo "Branch merge verified successfully."