name: CI/CD Pipeline with Branch Protection

on:
  push:
    branches: [test1, test2, master]
  pull_request:
    branches: [test1, test2, master]

jobs:
  # Block direct pushes to protected branches
  block-direct-pushes:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(fromJson('["refs/heads/master", "refs/heads/test1", "refs/heads/test2"]'), github.ref)
    steps:
      - name: Block direct push
        run: |
          echo "::error::Direct pushes to protected branches are not allowed. Please create a pull request."
          exit 1

  # Build and test workflow
  build-and-test:
    runs-on: ubuntu-latest
    needs: block-direct-pushes
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(fromJson('["refs/heads/master", "refs/heads/test1", "refs/heads/test2"]'), github.ref))
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Run linting
        run: npm run lint
          
      - name: Run tests
        run: npm test
        env:
          CI: true
          
      - name: Build project
        run: npm run build

  # Require manual approval for merging to protected branches
  manual-approval:
    if: github.event_name == 'pull_request' && contains(fromJson('["master", "test1", "test2"]'), github.base_ref)
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        run: |
          echo "This PR requires manual approval before merging"
          echo "Please review the changes and approve the workflow run"
        if: github.event_name == 'pull_request'
        
      # The following step is a placeholder; actual PR approval should be enforced via branch protection or workflow run approval
      - name: Ready for merge
        if: github.event_name == 'pull_request'
        run: echo "PR ready for merge after manual approval"